CREATE TABLE Cliente(
  id INT PRIMARY KEY AUTO_INCREMENTAL,
  nombre VARCHAR(255),
  apellidos VARCHAR(255),
  email VARCHAR(255)
);

CREATE TABLE Pedido(
  id INT PRIMARY KEY AUTO_INCREMENTAL,
  CONSTRAINT fk_formacion_1 FOREIGN KEY
)